# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Wimme' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Wimme
pod 'Firebase/Core'
pod 'Firebase/Database'
pod 'Firebase/Auth'

  target 'WimmeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'WimmeUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
